### ISSUE TITLE
Discord OAuth | Display avatar

### ISSUE THREAD

**Issue by Behold3th** [BanklessDAO/bounty-board#104]
Discord OAuth has been implemented in feature/95_discord-oauth. Due to resource constraints, I have to pivot to the Multi-Tenancy story. There are additional UX features to implement to complete this story. 

**Describe the solution you'd like**
Display Discord PFP. Using the user object returned in the Discord OAuth flow, query the discord CDN for a user's avatar and display in place of the 'Join DAO' button. Display avatar as 30 x 30 pixels, and display the username and discriminant next to it like in the example from sesh bot in the third image below.

<img width="1440" alt="Screen Shot 2021-10-13 at 4 50 12 PM" src="https://user-images.githubusercontent.com/85538143/137210795-9a6406d6-b576-4b33-9659-d8db1571cac1.png">
<img width="1440" alt="Screen Shot 2021-10-13 at 4 50 19 PM" src="https://user-images.githubusercontent.com/85538143/137210796-e655f1f0-7c37-4d4c-bff4-88f0c8d0650e.png">
<img width="238" alt="Screen Shot 2021-10-13 at 4 53 17 PM" src="https://user-images.githubusercontent.com/85538143/137212853-86acab37-6a30-4169-9da0-c94064ae8ebb.png">

Links to the discord avatars for a user reside in a link like: cdn.discordapp.com/avatars/464797917350461450/0026f9b54f6b07470103fc61df071f3a.png
`https://cdn.discordapp.com/avatars/user_id/user_avatar.png`

Documentation: https://discord.com/developers/docs/reference#image-formatting-cdn-endpoints

The user object returned by the discord object has the following fields (my user object as an example):
accent_color: 16557085 
avatar: "0026f9b54f6b07470103fc61df071f3a"" 
banner: null 
banner_color: "#fca41d" 
discriminator: "1111"
 flags: 0 
id: "464797917350461450" 
locale: "en-US" 
mfa_enabled: true
public_flags: 0
 username: "Behold"

The changes for OAuth have been implemented in `src/components/global/Header/index.tsx`

To close this issue, submit a PR from your local branch to feature/95_discord-oauth

**Comment by tescher** [comment]
Completed
