### ISSUE TITLE
Implement Multitenancy

### ISSUE THREAD

**Issue by Behold3th** [BanklessDAO/bounty-board#106]
To release the Bounty Board to external customers (i.e. DAOs other than Bankless) we will need to make changes to our data model, infrastructure, backend, and frontend code.

**General strategy**:
All bounty board customers go to bountyboard.bankless.community. When they authenticate with discord, we can get the list of servers they are in. If one of the servers is one of our customers, we present the option for the user to toggle to that customer’s bounty board.

 As customers onboard with First Quests, we will deploy a togglable front end option for that customer. I’m imagining a popup when you click on the Bankless logo that displays a list of other servers that you can select a bounty board from. A customer will give us a logo and their primary color - no admin console.

[Rest of description WIP]
**Design Decisions**

- Data model: The mongo recommended multitenancy strategy for our use case is a single database with a single set of collections for all customers. All inserted or upserted documents will include a unique `customer_id` with an acceptable degree of randomness.

**Describe the solution you'd like**
Add primary color as a configurable input : https://github.com/BanklessDAO/bounty-board/issues/108
Add DAO logo as a configurable input : https://github.com/BanklessDAO/bounty-board/issues/109
Add customerId as inserted field in back-end:
Filter by customerId for bounties on front-end:
Add smaller DAO logo as toggle avatar : 
Add customer specified guilds as a configurable input : 

**Describe alternatives you've considered**

**Additional context**

**Comment by jordaniza** [comment]
Implemented in the recent release
