### ISSUE TITLE
Application error: a client-side exception has occurred (developer guidance)

### ISSUE THREAD

**Issue by Behold3th** [BanklessDAO/bounty-board#107]
**Describe the bug**
Application error: a client-side exception has occurred (developer guidance)
Degen provides a discord user ID instead of the discord username? - can't reproduce so not 100% sure

**To Reproduce**
1. Go to bountyboard.bankless.community
2. Click on a bounty
3. Grab the HashID of the bounty
4. Navigate to bountyboard.bankless.community/HashID

**Expected behavior**
A 400 level error page

**Screenshots**
<img width="1083" alt="Screen Shot 2021-10-14 at 11 56 26 PM" src="https://user-images.githubusercontent.com/85538143/137429991-8ca893c7-d1f3-4e8d-9579-a9a1d323ab49.png">
<img width="1440" alt="Screen Shot 2021-10-14 at 11 57 34 PM" src="https://user-images.githubusercontent.com/85538143/137429993-b56518c2-510e-42fb-8f21-da9a0eccc8c9.png">

**Comment by jordaniza** [comment]
@Behold3th I think these are related https://github.com/BanklessDAO/bounty-board/issues/94

**Comment by Behold3th** [comment]
The error is:

```
Cannot read properties of undefined (reading 'discordHandle')
    at y (479-840c7b405d0a0c8d7e22.js:1)
    at ro (framework-4a390be9e05d1ffd8525.js:1)
    at Hu (framework-4a390be9e05d1ffd8525.js:1)
    at Pi (framework-4a390be9e05d1ffd8525.js:1)
    at xi (framework-4a390be9e05d1ffd8525.js:1)
    at _i (framework-4a390be9e05d1ffd8525.js:1)
    at vi (framework-4a390be9e05d1ffd8525.js:1)
    at framework-4a390be9e05d1ffd8525.js:1
    at t.unstable_runWithPriority (framework-4a390be9e05d1ffd8525.js:1)
    at $l (framework-4a390be9e05d1ffd8525.js:1)

```

Note that `/api/bounties/[id]` successfully fetches the correct bounty



Tagging @jordaniza - agreed?

**Comment by jordaniza** [comment]
Same issue as with single bounty id, fixed
