### ISSUE TITLE
Feedback & Need Help links are reversed

### ISSUE THREAD

**Issue by ryanburr** [BanklessDAO/bounty-board#120]
**Describe the bug**
The link for the "Give us Feedback" is to the [support Discord channel](https://discord.com/channels/834499078434979890/834499078434979893) and the link for the "Need Help?" button is to the [feedback form](https://forms.gle/NhTrynZ8pkkepHzN8).

**To Reproduce**
1. Navigate to https://bountyboard.bankless.community/
2. Click on "Give us Feedback"
  a. bug: you are taken to the support channel
3. Click on "Need Help?"
  a. bug: you are taken to the feedback form 

**Expected behavior**
These links should be reversed. "Give us Feedback" should link to the feedback form and the "Need Help?" button should link to the support channel.

**Desktop (please complete the following information):**
- OS: Windows
- Browser: Chrome
- Version: 95.0.4638.54

**Comment by jordaniza** [comment]
Merged and fixed, closing
