### ISSUE TITLE
Rethink inclusion of  `season` top-level field

### ISSUE THREAD

**Issue by Behold3th** [BanklessDAO/bounty-board#128]
Currently, `season` is a top level field for bounties that marks the season a bounty was created in. 

https://github.com/BanklessDAO/discord-bots : `CreateNewBounty.ts`

As we migrate to multi-tenancy, we expect customers to not have consistent seasons with BanklessDAO. As well, customers may not use seasons or a similar concept. 

The field is helpful for our analytics shareholders, however, the season number can be computed by performing a range query with ISO 8601 date-time values. Thus we have redundant data in our source of truth, which can lead to state invalidation.

Explicitly using the `season` field would require collection of season and date information from customers, and updating our `customers` collection with this information for each new season a customer would experience (since it's not guaranteed that seasons have equal lengths).  It is also an unnecessary stressor on our go-to-market. 

I recommend we remove storing the `season` field as part of our bounty data.

**Comment by jordaniza** [comment]
Assuming we are in a v0.x I would support this breaking change. Having fields unique to Bankless is going to cause technical debt as we deploy across tenants. To my knowledge, this feature is not heavily used.

**Comment by Behold3th** [comment]
Agree with your call out for caution around a breaking change - as of now,
I believe Paul is the only consumer of that field.

Let’s go ahead and have this implemented for the upcoming release.
Afterwards, we may not have the luxury to do so

**Comment by jordaniza** [comment]
Closing as the field is now deprecated
