### ISSUE TITLE
Creating a bounty didn't post to #bounty-board and clicking claim on the front end refreshes the front page

### ISSUE THREAD

**Issue by Icedcool** [BanklessDAO/bounty-board#133]
**Describe the bug**
Created a bounty and Degen didn't create a bounty in the #bounty-board channel. 
Currently unable to claim.

**To Reproduce**
1. /bounty create Bounty Board Outreach Proposal 1000
2. Defined the details and criteria
3. Click DRAFT
3. Modify the description
4. Create
5. Bounty is NOT created in #bounty-board channel and when hovering over the claim it button, it references the https://bountyboard.bankless.community

**Expected behavior**
When drafting and creating, the bounty is posted to #bounty-board channel.

**Screenshots**
![image](https://user-images.githubusercontent.com/50239591/140803319-9e2c8394-f98c-4754-ba24-867bc1bf1f68.png)

**Comment by Icedcool** [comment]
Attempted to claim via /bounty claim bounty-id: 61896f4f5f6f5200201b38d1I and received this error:
![image](https://user-images.githubusercontent.com/50239591/140803648-dfdfbc21-f9b3-40b2-a8a0-0b18d53905dc.png)

Although, Links tried it twice, and it eventually was claimed. He also clicked claim it on the front end.
Maybe it refreshed?

**Comment by jordaniza** [comment]
I think this is related to bountybot + some old integrations. Either way doesn't seem to be a persistent issue so closing
