### ISSUE TITLE
Default show OPEN on the web frontend

### ISSUE THREAD

**Issue by almithani** [BanklessDAO/bounty-board#134]
Currently, when you load the  bounties on the [web frontend](https://bountyboard.bankless.community/), it shows ALL bounties.  This means that the user is presented with bunch of bounties that have nothing to do with them, and aren't really interesting.   In fact, it can be confusing to the user if they don't understand the possible states - they can't find bounties they expect to see there (as per the session linked below).

Ideally, only OPEN bounties would be shown to start, and there would be some way to learn what each state means.

Identified in [Writer's Guild Liaison session](https://www.notion.so/bankless/8b394ce753f84f85a9423766fc47c046?v=31fd75495ad14f7297f0fb7514932ccf&p=ab49edbe08984f5699651d23acc83bd4).

**Comment by jordaniza** [comment]
This is fixed in the incoming release!
