### ISSUE TITLE
Search bar doesn't work on web frontend

### ISSUE THREAD

**Issue by almithani** [BanklessDAO/bounty-board#135]
Steps to reproduce

1. Access https://bountyboard.bankless.community/
2. Type any letter into the search bar
ACTUAL:  All bounties are eliminated
EXPECTED: bounties containing (or at least starting with) the letter are shown

**Comment by jordaniza** [comment]
Second, this is due to MongoDB text indexing being kinda rubbish. We need a proper text indexing service to power search

**Comment by jordaniza** [comment]
yep
