### ISSUE TITLE
Discord handles are mangled in web frontend

### ISSUE THREAD

**Issue by almithani** [BanklessDAO/bounty-board#136]
**Steps to reproduce**
1. Use DEGEN to create a new bounty, copying your discord handle into the text as a link (i.e. contact links#7868 when completed)
2. View your bounty on the web frontend: https://bountyboard.bankless.community/
**ACTUAL**: your discord handle shows up as a string of numbers
**EXPECTED**: your human-readable discord handle (or even better, a link to msg on discord)

**Comment by jordaniza** [comment]
I believe this issue has been addressed, or at least haven't seen in a while. closing
