### ISSUE TITLE
Bounty detailed view shows 404 instead of loading

### ISSUE THREAD

**Issue by Behold3th** [BanklessDAO/bounty-board#145]
**Describe the bug**
While loading a detailed view of a given bounty, the 404 not found screen is shown before the bounty loads, instead of displaying a loading page. 

**To Reproduce**
1. Go to bountyboard.bankless.community
2. Click on a bounty
3. Copy the `HashID`
4. Go to `bountyboard.bankless.community/[HashID] (omit the brackets when pasting)
5. Observe the 404 screen while the bounty is loading

**Expected behavior**
Display a loading page instead of 404.

**Screenshots**
[If applicable, add screenshots to help explain your problem.](https://www.loom.com/share/6992259f3c4c4e2084b0992f846a47e9)

**Desktop (please complete the following information):**
- OS: MacOs
- Browser chrome]

**Comment by jordaniza** [comment]
resolved with skeleton loaders
