### ISSUE TITLE
Edit after /bounty create

### ISSUE THREAD

**Issue by PaulApivat** [BanklessDAO/bounty-board#148]
**Describe the feature under construction**

After successfully creating a bounty in BBBS using the `/bounty create` command, user enters bounty description, criteria for completion and date. *Then* the user might want to edit. Currently this is under construction.

**To Reproduce**
1. Go to 'BBBS cheese-bounty-board channel'
2. Click  '/bounty create' and receive a DM.
3. Provide follow-up info including: bounty description, criteria for completion and date.
3. Scroll down to 'notepad / pencil emoji' to edit
4. See prompt that feature is under construction.

**Expected behavior**
Option 1: Divert users to front end (test-bountyboard.bankless.community) to edit (mode) of the bounty card they just created.

Option 2: Allow bounty editing in discord. Within DM between user and Bounty-bot allow edits to bounty card. 

**Screenshots**

![Screen Shot 2021-12-01 at 15 41 27](https://user-images.githubusercontent.com/4058461/144200781-87fea1b4-a63d-4218-a7df-78f05e70c8c2.png)

**Desktop (please complete the following information):**
- OS: macOS version 11.4
- Browser: Chrome
- Version: Version 96.0.4664.55 (Official Build) (x86_64)

**Comment by jordaniza** [comment]
Addressed in #209
