### ISSUE TITLE
List of open bounties on Discord is different from the bounty board

### ISSUE THREAD

**Issue by tsioureth** [BanklessDAO/bounty-board#196]
**Describe the bug**
Hi,
The open bounties list on the discord is different from the ones on the website.

**To Reproduce**
1. Go to [https://bountyboard.bankless.community/](https://bountyboard.bankless.community/)
At this time (13/02/22, 07:06 UTC), there are 3 open bounties : Bounty Board UX review, "Join the Translators Guild" and Join Employment Commons
![image](https://user-images.githubusercontent.com/59292776/153741092-f64d2639-f2aa-41a9-b357-9e342aeb31ab.png)

2. By contrast, in the #🧀-bounty-board channel in the discord, when I do the "/bounty list list-type:open" command, BountyBot lists me theses : 
![image](https://user-images.githubusercontent.com/59292776/153741193-c7fa5cc6-6278-4e5d-9c82-e04d424b1413.png)
![image](https://user-images.githubusercontent.com/59292776/153741197-c6865adf-025a-4336-856c-538f137c214c.png)

The only common task is the "Bounty Board UX review".

**Expected behavior**
See the exact same list of open bounties

**Screenshots**
See the description above

**Desktop (please complete the following information):**
- OS: Windows 10 Professionnel 21H2 64bits
- Browser: Brave
- Version: 1.35.101 (Chromium: 98.0.4758.87)

**Additional context**
- Discord version : Stable 114407 (811ab09)

**Comment by jordaniza** [comment]
Thank you @tsioureth, we think this was due to a renaming of a field in some of the bounties. PR #201 should address this

**Comment by jordaniza** [comment]
Fixed in #201
