### ISSUE TITLE
Is it okay to fork this for another DAO?

### ISSUE THREAD

**Issue by hunterchristian** [BanklessDAO/bounty-board#200]
I'm cautiously stepping into the DAO/crypto world and am looking to set up a DAO for my startup: https://joincottage.com

Would you mind if I fork this repo and use it to track bounties for the development of my platform? It will be open and accessible to anyone who applies, in accordance with the open web.

**Comment by jordaniza** [comment]
@hunterchristian I am closing this issue as I believe you spoke to @Icedcool about it.
