### ISSUE TITLE
Should not show 404 on loading bounty page 

### ISSUE THREAD

**Issue by thedarkrai07** [BanklessDAO/bounty-board#234]
**Describe the bug**
When we are viewing a bounty page, we see a 404 page for a split second

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to https://bountyboard.bankless.community/61b21cf5e68d920049e55485
2. First it shows skeleton loading
3. Then it shows 404
4. Bounty loads

**Expected behaviour**
404 screen should not appear

**Screenshots**
<img width="1011" alt="image" src="https://user-images.githubusercontent.com/105098416/168193537-b9c1cbf1-4981-424f-8c19-9cfe1e7478f1.png">

**Comment by tescher** [comment]
Start by looking here: https://github.com/BanklessDAO/bounty-board/blob/main/packages/react-app/src/pages/%5Bid%5D/index.tsx
