### ISSUE TITLE
Missing yarn dependency

### ISSUE THREAD

**Issue by thedarkjester** [BanklessDAO/bounty-board#260]
**Describe the bug**

The following is missing as a dependency when trying to run and install the site on a fresh machine.

```
esprima@substack/esprima#is-keyword:
  version "1.1.0-dev"
  resolved "https://codeload.github.com/substack/esprima/tar.gz/0a7f8489a11b44b019ce168506f535f22d0be290"
```

Additionally, it says to post the data from the yarn error log file which does not exist
```
#11 27.35 info If you think this is a bug, please open a bug report with the information provided in "/bountyboard/yarn-error.log".
```

**To Reproduce**
1. Start on a fresh machine or possibly remove/rename your package cache if you have the file in there
2. Run `docker compose up`
3. See error in the terminal output

**Expected behavior**
I expected the yarn package to exist, the code to compile and the site to spin up.

**Screenshots**
![image](https://user-images.githubusercontent.com/3957173/200564885-bdaaeb74-7e75-47af-a97e-4ed5e0e786fd.png)

**Desktop (please complete the following information):**
- OS: Windows (building on WSL2)
- Browser n/a
- Version n/a

**Smartphone (please complete the following information):**
- Device:  n/a
- OS:  n/a
- Browser  n/a
- Version  n/a

**Additional context**
There are no yarn packages at all on my setup, so it is likely existing devs have it working with a cached package

**Comment by tescher** [comment]
Thanks. Which branch did you find this on? In main? I think I dealt with this in develop

**Comment by thedarkjester** [comment]
Correct - this is on main - I forked the repo, pulled and tried to get it running.

**Comment by tescher** [comment]
Fixed as part of other commit
