### ISSUE TITLE
Implement searching and filters for bounties

### ISSUE THREAD

**Issue by Oktalize** [BanklessDAO/bounty-board#35]
## Description
We will need to implement functionality for searching and filtering the bounties.

## Files
`components/pages/Bounties/Filters`
`pages/api/bounties/index.ts`

## API Implementation 
- [x] Search query function
- [x] Filter by Status
- [ ] Filter by Bounty Reward Value (min & max) 
- [ ] Filter by Guilds (once implemented on the backend)

## Component Implementation
- [x] Search input with debounce
- [x] Filter by Status
- [ ] Filter by Bounty Reward Value (min & max)
- [ ] Filter by Guilds (once implemented on the backend)
- [ ] Sort by Bounty Reward Value (ascending & descending)

# Screenshot examples

## Guild filters
![CleanShot 2021-09-21 at 19 17 58](https://user-images.githubusercontent.com/81541283/134264133-54800fc3-3aad-4433-8c45-7a67170bf6d4.png)

## Sort filters
![CleanShot 2021-09-21 at 19 18 34](https://user-images.githubusercontent.com/81541283/134264155-b63297cc-a2fa-4785-89ba-af69993ff53a.png)

## Value filters
![CleanShot 2021-09-21 at 19 18 56](https://user-images.githubusercontent.com/81541283/134264175-fab11d9a-f77c-4253-8c81-09de92644360.png)

**Comment by jordaniza** [comment]
@Oktalize other filters aside from guild have been applied

**Comment by jordaniza** [comment]
Closing this, as it has been part open for too long. 

Please open a separate PR for guilds once gating has been implemented
