### ISSUE TITLE
Fix Netlify to build correctly

### ISSUE THREAD

**Issue by Oktalize** [BanklessDAO/bounty-board#37]
## Description
I noticed after deploying my PR that Netlify gives a 404 error when trying to load the preview page. I think that there may be something wrong with the output pathing because of `yarn` workspaces but I am not sure. 

## Next steps
Review the logs and possibly try to find out what is going on.

**Comment by Oktalize** [comment]
While we are at it we should make sure the mongoDB connection is setup correctly.

**Comment by amaredeus** [comment]
Might be an issue with .toml configuration. @joaoh9 mentioned that maybe we can copy the output directory and I'm wondering if how netlify looks for the dist folder we can configure that path

**Comment by amaredeus** [comment]
#48 fixes this!
