### ISSUE TITLE
ReactJS basic template

### ISSUE THREAD

**Issue by amaredeus** [BanklessDAO/bounty-board#4]
Create a ReactJS basic template to display a html/css table.

**Comment by Oktalize** [comment]
I am going to work on getting a good starting point for us here. On the dev guild weekly call @Tgriffith3433 mentioned using the NextJS boilerplate he made for the NFT project. So that should be a good place for us to start.

PR will be incoming when complete.

**Comment by amaredeus** [comment]
Sounds good! Also there is a popular boilerplate code used in hackathons as in case you want to go big https://github.com/austintgriffith/scaffold-eth

**Comment by amaredeus** [comment]
Closing as the template has been merged
