### ISSUE TITLE
Add "Give us Feedback" and "Get Help" Links

### ISSUE THREAD

**Issue by Oktalize** [BanklessDAO/bounty-board#54]
## Description
The bottom of the filters list has two buttons. One for "**Give us Feedback**" and one for "**Get Help**" (see screenshot). These do not currently work.

## Solution
For MVP we want to link these to Discord channels.

## Possible blocked by
We do not know which Discord channels to use.

## Screenshot
![CleanShot 2021-08-09 at 22 29 03](https://user-images.githubusercontent.com/81541283/128804268-8e01d04e-032d-4a2c-a035-91a4538f4b08.png)

**Comment by Oktalize** [comment]
Also MrPackman has suggested to change "? Get Help" to "Need Help?" which makes more sense.

**Comment by amaredeus** [comment]
Let's use the top level #support channel as the go to link for help. Keep things simple

**Comment by Behold3th** [comment]
I propose feedback link to a google form initially, and once we've reached a stable release (low velocity of bug reports) can move to github issues. Maintaining a channel will be a high overhead energy and time cost, and to guide prioritization we want to be able to aggregate and group reports

**Comment by amaredeus** [comment]
@Oktalize @Behold3th Can this be closed?
