### ISSUE TITLE
Integrate with Discord OAuth2

### ISSUE THREAD

**Issue by Behold3th** [BanklessDAO/bounty-board#95]
In order to build front-end functionality for creating and claiming bounties while keeping discord as the identity provider, Bounty Board will need to integrate Discord OAuth2 to authenticate future users and be granted authorization to perform operations on behalf of the user. 

Until Connect Wallet functionality is implemented and displayed, the Discord OAuth2 status can be displayed in the same location as the "Join DAO" button above the "DAO Bounty Board" title - and we can override the button to join the Bankless server if the user is not already a member.

When first loading `bountyboard.bankless.community`, the user will be requested to authenticate with Discord OAuth2. This decision can be revisited when Connect Wallet auth is added.

Issue 105: [merged, author: @mosejs]
------------
https://github.com/BanklessDAO/bounty-board/issues/105
------------

Issue 104: [in flight, author: @moshejs]
------------
https://github.com/BanklessDAO/bounty-board/issues/104

**Comment by jordaniza** [comment]
Implemented in latest merge, closing
